# This is a basic check on build of this repo

name: MATLAB Build

# Controls when the action will run. 
on:
  # Triggers the workflow on push
  push:
    branches: [ main ]
    paths-ignore:
      - 'images/**'
      - 'resources/**'
      - '.gitattributes'
      - '.gitignore'
      - 'license.txt'
      - 'README.md'
      - 'SECURITY.md'

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4

      # Handle display using a virtual display
      - name: Start display server
        run: |
          sudo apt-get install xvfb
          Xvfb :99 &
          echo "DISPLAY=:99" >> $GITHUB_ENV
      
      # Sets up MATLAB on the GitHub Actions runner
      - name: Setup MATLAB
        uses: matlab-actions/setup-matlab@v2
        products: |
              Simulink 
              Navigation_Toolbox 
              Computer_Vision_Toolbox
              Image_Processing_Toolbox
              Automated_Driving_Toolbox
              Stateflow
              Robotics_System_Toolbox
              Simulink_3D_Animation
              Model_Predictive_Control_Toolbox

      # Runs a set of commands using the runners shell
      - name: Run all tests
        uses: matlab-actions/run-tests@v2
        with:
          source-folder: Helpers; SimModels